### ISSUE TITLE
developer

### ISSUE THREAD

**Issue by ccodling100** [libracore/ERPNextSharp#3]
I'm getting an "Internal Server Error" when running the unit tests. Login works, but inserting a customer does not.  Is there something that needs to be enabled on the ERPNext server to allow the API to insert a customer?

**Comment by lasalesi** [comment]
Do you have more information on the 500 Internal Server Error? I presume connection to the server works fine. There is one open issue which is on error 500 (subtable json, issue #2). Does the role you use to log in have create rights on customer?
